### ISSUE TITLE
Tabbing does not work

### ISSUE THREAD

**Issue by marchbnr** [furqanZafar/react-selectize#25]
Tabbing through the elements on the example page does not work.
Once you hit the first react-selectize element and hit tab, the focus will jump back to the first element on the page.

(I had to remove the text fields)

**Comment by furqanZafar** [comment]
fixed in release 0.5.1, thanks for pointing it out :) 

you can paste this in the JSX live editor for testing:
```
// MultiSelect = require("react-selectize").MultiSelect

Form = React.createClass({
    
    // render :: a -> ReactElement
    render: function(){
        var self = this, 
            options = ["apple", "mango", "grapes", "melon", "strawberry"].map(function(fruit){
                return {label: fruit, value: fruit}
            });
        return <div>
            <MultiSelect 
                options = {options} 
                placeholder = "Select fruits"
                onEnter = {() => {
                    findDOMNode(this.refs.dummy).focus();
                }}/>
            <input type="text" ref="dummy"/>
        </div>
    }
    
});

render(<Form/>, mountNode)
```

**Comment by marchbnr** [comment]
Wow, that was quick! Thanks for the fast reply! I have tested 0.5.1 and it works!

**Comment by akheron** [comment]
Tabbing still doesn't work if you select something (at least in a SimpleSelect) by pressing enter and then try to tab to the next select. It goes to the first element on the page.

Without pressing enter and just tabbing between selects works as expected.

**Comment by furqanZafar** [comment]
Fixed in `0.6.0`. Thanks

**Comment by akheron** [comment]
Works like a charm, thanks!
